sudo: required
services:
  - docker

before_install:
  - docker build -t hekme5/docker-react -f Dockerfile.dev .

script:
  - docker run hekme5/docker-react npm run test 
  #-- --coverage

# http://dockerreact1-env.iq7h8bkhpj.us-east-1.elasticbeanstalk.com/
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: docker-react-1
#   env: "DockerReact1-env"

