sudo: required
services:
  - docker

before_install:
  - docker build -t hekme5/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hekme5/docker-react npm run test -- --watchAll=false
  # - docker run hekme5/docker-react npm run test -- --coverage

# http://dockerreact1-env.iq7h8bkhpj.us-east-1.elasticbeanstalk.com/
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-react-1
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-1-016835203806"
  bucket_path: "docker-react-1"
  on:
    branch: "master"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

